fix readthedocs build
started installing numpy 1.20 release candidate, which requires python
3.7.

```
  File "/tmp/easy_install-1pnmpbr9/numpy-1.20.0rc1/setup.py", line 30, in <module>

RuntimeError: Python version >= 3.7 required.
```

given that aiida-core is also following the numpy support cycle, which
will drop python 3.6 support on Jan 21 2021, we can do this here as
well.